keys:
  - &admin age1tayhzuek77fz3upl660utx6pn9fhzck9fe77lzqe5vwellrafytswluxzh
  - &playground age1quhxu8lptht4lczlqeu9dqd930d9ht6wqnsyzttecx37lkezxusqg9wd9z
creation_rules:
  - path_regex: modules/secrets/secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *playground
